//! First-party operational events on the installation resource.
//!
//! These are statements the product is authoritative about itself. They use the
//! organization-nominated platform resource from `docs/self-monitoring.md`; organizations
//! that have not nominated one retain their existing behavior and simply receive no event.

mod seen;

use std::collections::{BTreeMap, HashSet};
use std::future::Future;
use std::time::Duration;

use chrono::{DateTime, Utc};
use uops_core::{OrgId, SiteId, TenantId};
use uops_store_ch::{EventRow, EventStore, ChStore};
use uops_store_pg::{Job, PgStore, PlatformTarget};

use crate::seen::Seen;

/// One event generated by this product about its own operation.
#[derive(Clone, Debug)]
pub struct PlatformEvent<'a> {
    pub category: &'a str,
    pub event_type: &'a str,
    pub severity: &'a str,
    pub summary: String,
    pub attributes: BTreeMap<String, String>,
    pub occurred_at: DateTime<Utc>,
}

/// One event as a telemetry row.
fn row(target: PlatformTarget, event: PlatformEvent<'_>, ingested_at: DateTime<Utc>) -> EventRow {
    EventRow {
        tenant_id: target.tenant_id,
        resource_id: target.resource_id,
        site_id: SiteId::nil(),
        observed_at: event.occurred_at,
        ingested_at,
        source_kind: "self".to_owned(),
        source_vendor: String::new(),
        severity: event.severity.to_owned(),
        event_category: event.category.to_owned(),
        event_type: event.event_type.to_owned(),
        summary: event.summary,
        attributes: event.attributes,
    }
}

/// Write one event to a known platform target. Telemetry failure is returned so callers
/// can log it, but must never fail the operation that produced the event.
///
/// # Errors
///
/// Whatever `ClickHouse` said.
pub async fn emit(
    ch: &ChStore,
    target: PlatformTarget,
    event: PlatformEvent<'_>,
) -> Result<(), uops_store_ch::Error> {
    EventStore::insert_events(ch, &[row(target, event, Utc::now())]).await
}

/// Emit an event to the nominated resource for one organization, if configured.
///
/// `false` when the organization has nominated no resource. Not an error: the caller is
/// saying where to put an event and "nowhere" is a complete answer.
///
/// # Errors
///
/// Whatever the stores said.
pub async fn emit_for_org(
    pg: &PgStore,
    ch: &ChStore,
    org: OrgId,
    event: PlatformEvent<'_>,
) -> Result<bool, uops_core::Error> {
    let Some(target) = pg.platform_target(org).await? else {
        return Ok(false);
    };
    emit(ch, target, event)
        .await
        .map_err(|e| uops_core::Error::Storage(format!("writing platform event: {e}")))?;
    Ok(true)
}

/// Emit an event to every organization that has nominated its platform resource.
///
/// **One insert, not one per organization.** An earlier version looped and inserted
/// separately, which a test against a database holding several thousand organizations
/// turned into an eight-minute lease handover. `ClickHouse` is a column store and a
/// single-row insert is its worst case; a deployment-wide event is by definition the same
/// statement about every organization, so it is one write.
///
/// The consequence is that this is all-or-nothing rather than best-effort per organization.
/// That is the honest semantic for a batch, and every row here is generated by this product
/// from one template — there is no bad row that a good one needs protecting from.
///
/// # Errors
///
/// Whatever the stores said.
pub async fn emit_to_all(
    pg: &PgStore,
    ch: &ChStore,
    event: impl Fn(OrgId) -> PlatformEvent<'static>,
) -> Result<(), uops_core::Error> {
    let targets = pg.platform_targets().await?;
    if targets.is_empty() {
        return Ok(());
    }

    // One `ingested_at` for the batch: they were ingested together, and stamping each row
    // separately would record a spread that is an artefact of building the vector.
    let ingested_at = Utc::now();
    let rows: Vec<EventRow> = targets
        .into_iter()
        .map(|(org, target)| row(target, event(org), ingested_at))
        .collect();

    EventStore::insert_events(ch, &rows)
        .await
        .map_err(|e| uops_core::Error::Storage(format!("writing platform events: {e}")))
}

/// Build standard attributes for a first-party event.
#[must_use]
pub fn attributes(pairs: impl IntoIterator<Item = (String, String)>) -> BTreeMap<String, String> {
    pairs.into_iter().collect()
}

/// Find the platform target corresponding to a tenant-specific event.
pub async fn target_for_tenant(
    pg: &PgStore,
    tenant: TenantId,
) -> Result<Option<(OrgId, PlatformTarget)>, uops_core::Error> {
    pg.platform_target_for_tenant(tenant).await
}


/// Observe the small set of persisted facts named in `docs/self-monitoring.md` §4 and
/// write changes as first-party events. A PostgreSQL advisory lock makes this one observer
/// even when the API has several replicas. The lock is session-scoped and is released if
/// the process or connection disappears.
///
/// What is *not* an event is as much of the design as what is. Each tick reads current
/// state; [`Seen`] decides which of it is news. See that module for why the three facts
/// remember differently.
pub async fn run<F>(pg: PgStore, ch: ChStore, shutdown: F)
where
    F: Future<Output = ()> + Send,
{
    const LOCK: i64 = 728_541_890_021;
    let mut shutdown = std::pin::pin!(shutdown);
    let mut connection = loop {
        tokio::select! {
            () = &mut shutdown => return,
            result = pg.pool().acquire() => match result {
                Ok(mut connection) => {
                    let acquired = sqlx::query_scalar::<_, bool>("SELECT pg_try_advisory_lock($1)")
                        .bind(LOCK)
                        .fetch_one(&mut *connection)
                        .await;
                    match acquired {
                        Ok(true) => break connection,
                        Ok(false) => drop(connection),
                        Err(error) => eprintln!("self-monitoring: cannot acquire observer lock: {error}"),
                    }
                }
                Err(error) => eprintln!("self-monitoring: cannot connect to PostgreSQL: {error}"),
            }
        }
        tokio::select! {
            () = &mut shutdown => return,
            () = tokio::time::sleep(Duration::from_secs(10)) => {}
        }
    };

    let mut seen = Seen::default();
    let mut tick = tokio::time::interval(Duration::from_secs(30));
    tick.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);

    loop {
        tokio::select! {
            () = &mut shutdown => return,
            _ = tick.tick() => {}
        }

        observe_collectors(&pg, &ch, &mut seen).await;
        observe_leases(&pg, &ch, &mut seen).await;
        observe_failed_runs(&pg, &ch, &mut seen).await;

        // Keep the advisory-lock connection checked out for the whole observer lifetime.
        // This read is intentionally trivial: it detects a broken connection so a replica
        // that lost its lock does not keep publishing duplicate events.
        if let Err(error) = sqlx::query_scalar::<_, i32>("SELECT 1")
            .fetch_one(&mut *connection)
            .await
        {
            eprintln!("self-monitoring: observer lock connection failed: {error}");
            return;
        }
    }
}

/// M12 §2.3 has the data and a screen for a collector that stopped heartbeating, and no
/// alert. This is the alert.
async fn observe_collectors(pg: &PgStore, ch: &ChStore, seen: &mut Seen) {
    let targets = match pg.platform_targets().await {
        Ok(targets) => targets,
        Err(error) => {
            eprintln!("self-monitoring: could not read platform targets: {error}");
            return;
        }
    };

    // Accumulated across every organization before pruning, not per organization — see
    // `Seen::only_still_quiet`.
    let mut quiet_now = HashSet::new();
    let mut complete = true;

    for (org, _) in targets {
        let collectors = match pg.collectors(org).await {
            Ok(collectors) => collectors,
            Err(error) => {
                eprintln!("self-monitoring: could not read collectors for {org}: {error}");
                // This organization's quiet collectors are unknown this tick. Pruning on a
                // partial picture would forget them and report them again next tick.
                complete = false;
                continue;
            }
        };
        for collector in collectors
            .into_iter()
            .filter(|collector| collector.quiet && !collector.retired)
        {
            let Some(last_seen) = collector.last_seen_at else {
                continue;
            };
            quiet_now.insert(collector.id);
            if !seen.collector_quiet(collector.id, last_seen) {
                continue;
            }
            let event = PlatformEvent {
                category: "process",
                event_type: "end",
                severity: "warn",
                summary: format!(
                    "Collector stopped reporting: {} {}",
                    collector.kind.as_str(),
                    collector.name
                ),
                attributes: attributes([
                    ("collector.id".to_owned(), collector.id.to_string()),
                    (
                        "collector.kind".to_owned(),
                        collector.kind.as_str().to_owned(),
                    ),
                    ("collector.name".to_owned(), collector.name.clone()),
                    ("collector.last_seen_at".to_owned(), last_seen.to_rfc3339()),
                ]),
                // When it went quiet, not when this observer noticed. The tick is an
                // implementation detail and dating the event by it would put the estate's
                // timeline out by up to thirty seconds.
                occurred_at: last_seen + uops_store_pg::QUIET_AFTER,
            };
            if let Err(error) = emit_for_org(pg, ch, org, event).await {
                eprintln!(
                    "self-monitoring: could not record stopped collector {}: {error}",
                    collector.id
                );
                seen.collector_not_reported(collector.id);
            }
        }
    }

    if complete {
        seen.only_still_quiet(&quiet_now);
    }
}

/// A lease changing hands is how leader election looks from outside, and an operator
/// currently finds out by reading the `lease` table.
async fn observe_leases(pg: &PgStore, ch: &ChStore, seen: &mut Seen) {
    for job in [Job::Poll, Job::Alert, Job::Sweep, Job::Run] {
        let lease = match pg.lease_holder(job).await {
            Ok(lease) if lease.live => lease,
            // An expired lease is not a handover: nobody has taken it yet. The next live
            // read reports the move from whoever held it last.
            Ok(_) => continue,
            Err(error) => {
                eprintln!(
                    "self-monitoring: could not read {} lease: {error}",
                    job.as_str()
                );
                continue;
            }
        };
        let Some(previous) = seen.lease_moved(job, &lease.holder) else {
            continue;
        };
        let holder = lease.holder.clone();
        if let Err(error) = emit_to_all(pg, ch, move |_| PlatformEvent {
            category: "process",
            event_type: "change",
            // Ordinary, in the sense §4 gives the word: a rolling restart produces these.
            // There is no level meaning "alarming" because how alarming depends on how
            // many in how long, and that is a rule's business.
            severity: "warn",
            summary: format!("{} lease changed hands", job.as_str()),
            attributes: attributes([
                ("lease.job".to_owned(), job.as_str().to_owned()),
                ("lease.previous_holder".to_owned(), previous.clone()),
                ("lease.holder".to_owned(), holder.clone()),
            ]),
            occurred_at: Utc::now(),
        })
        .await
        {
            eprintln!(
                "self-monitoring: could not record {} lease handover: {error}",
                job.as_str()
            );
        }
    }
}

/// A runbook run that failed. Unlike the other two this is already a past event with a
/// timestamp of its own, so the only question is whether it has been announced.
async fn observe_failed_runs(pg: &PgStore, ch: &ChStore, seen: &mut Seen) {
    // Ten minutes, matched to nothing in particular: long enough that a tick cannot step
    // over a failure, short enough that a restart does not re-announce yesterday's.
    let runs = match pg.recently_failed_runs(chrono::Duration::minutes(10)).await {
        Ok(runs) => runs,
        Err(error) => {
            eprintln!("self-monitoring: could not read failed runs: {error}");
            return;
        }
    };

    let mut recent = HashSet::with_capacity(runs.len());
    for run in runs {
        recent.insert(run.id);
        if !seen.run_failed(run.id) {
            continue;
        }
        let Some((org, target)) = (match target_for_tenant(pg, run.tenant_id).await {
            Ok(target) => target,
            Err(error) => {
                eprintln!(
                    "self-monitoring: could not resolve platform target for failed run {}: {error}",
                    run.id
                );
                seen.run_not_reported(run.id);
                continue;
            }
        }) else {
            // No nominated resource for this organization. Not an error and not retried:
            // `docs/self-monitoring.md` says those installations simply receive no event.
            continue;
        };
        let event = PlatformEvent {
            category: "configuration",
            event_type: "failure",
            severity: "error",
            summary: format!("Runbook run failed: {}", run.runbook_id),
            attributes: attributes([
                ("run.id".to_owned(), run.id.to_string()),
                ("runbook.id".to_owned(), run.runbook_id.to_string()),
                ("run.tenant_id".to_owned(), run.tenant_id.to_string()),
                ("event.reason".to_owned(), run.failure.unwrap_or_default()),
            ]),
            occurred_at: run.finished_at,
        };
        if let Err(error) = emit(ch, target, event).await {
            eprintln!(
                "self-monitoring: could not record failed run {} for {org}: {error}",
                run.id
            );
            seen.run_not_reported(run.id);
        }
    }

    // Every id left in the memory that this query can no longer return is dead weight.
    seen.only_recent_runs(&recent);
}
